### ISSUE TITLE
Deprecated EDAnalyzer in BeamSpotProducer

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#24]
A recent PR touched on the BeamSpotProducer and so the Static Analyzer brought up a warning that the BeamSpotProducer is using a Deprecated EDAnalyzer
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23a921/18400/llvm-analysis/
More info about the legacy EDAnalyzer can be found in [*].

[*] https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedAnalysisEDAnalyzer

**Comment by mmusich** [comment]
This can be closed
