### ISSUE TITLE
Deprecated EDAnalyzer in DTCalibration

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#25]
As discussed here
https://github.com/cms-sw/cmssw/pull/35184#issuecomment-917138455
there are some deprecated EDAnalyzer in DTCalibration
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-422427/18493/llvm-analysis/legacy-mod-sa.txt

Will be follow-up by @swagata87 @namapane

**Comment by tvami** [comment]
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-09-2300/src/CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc:22:1: warning: DTTPAnalyzer inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule [deprecated.edmChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-09-2300/src/CalibMuon/DTCalibration/plugins/DTTTrigCalibration.h:33:1: warning: DTTTrigCalibration inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule [deprecated.edmChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-09-2300/src/CalibMuon/DTCalibration/plugins/DTVDriftCalibration.h:35:1: warning: DTVDriftCalibration inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule [deprecated.edmChecker]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-09-2300/src/RecoLocalMuon/DTSegment/src/DTRecSegment2DExtendedProducer.h:34:1: warning: DTRecSegment2DExtendedProducer inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule [deprecated.edmChecker]
```

**Comment by namapane** [comment]
Hi @tvami ,
As far as I can tell, RecoLocalMuon/DTSegment/src/DTRecSegment2DExtendedProducer.h is straightforward (just change to edm::stream::EDProducer<>). I am a bit unsure about the others; for example, for:
https://github.com/cms-sw/cmssw/blob/master/CalibMuon/DTCalibration/plugins/DTTTrigCalibration.h#L31
I suppose that should become a edm::global::EDAnalyzer, but do I understand correctly that some recording would then be necessary to ensure thread safety for members like theHistoMap at L75? 
If so, is it acceptable to migrate these modules to edm::one instead, especially sicne they are anyhow run only by calibration experts (ie manually and not in central workflows)?

**Comment by namapane** [comment]
(this is maybe a question for @Dr15Jones)

**Comment by Dr15Jones** [comment]
Probably better to use a `edm::one` as writing `edm::global::EDAnalyzer` usually requires expertise.

**Comment by namapane** [comment]
> 
> 
> Probably better to use a `edm::one` as writing `edm::global::EDAnalyzer` usually requires expertise.

Indeed that was my impression :-)
