### ISSUE TITLE
Deprecated ES get is called in Alignment/OfflineValidation

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#27]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0396e1/18596/summary.html

says
` Deprecated API | EventSetupRecord::get function called | /Alignment/OfflineValidation/plugins/TrackerOfflineValidationSummary.cc`

**Comment by mmusich** [comment]
For the record a corresponding es transition for the endJob does not exist: https://github.com/cms-sw/cmssw/pull/32005#discussion_r516713046.
You're welcome to find a workaround

**Comment by tvami** [comment]
> For the record a corresponding es transition for the endJob does not exist: [cms-sw/cmssw#32005 (comment)](https://github.com/cms-sw/cmssw/pull/32005#discussion_r516713046).

@makortel @Dr15Jones do you maybe have any suggestions on how to resolve that?

**Comment by makortel** [comment]
Accessing EventSetup products in endJob is not supported for long time (if ever). It possibly working in practice is an accident that may stop working at any time. The least bad workaround would be to for the module to copy the ESProduct (the product itself, not a pointer to it) into a member variable e.g. in endRun or endLumi, and use that in the endJob.

**Comment by mmusich** [comment]
see please https://github.com/cms-sw/cmssw/pull/35281.

**Comment by mmusich** [comment]
this can be closed now.
