### ISSUE TITLE
More deprecated EDAnalyzers / `EventSetupRecord::get`s  in DTCalibration

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#30]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0c9c1/18662/llvm-analysis/

```
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0WireInChamberReferenceCorrection.cc	48
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigMatchRPhi.cc	
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0ChamberReferenceCorrection.cc
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTVDriftSegmentCalibration.cc	62
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0AbsoluteReferenceCorrection.cc	46
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigWriter.cc	76
Deprecated API	EventSetupRecord::get function called	/RecoLocalMuon/DTSegment/src/DTClusterer.cc	65
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTNoiseCalibration.cc	99
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0FillChamberFromDB.cc	46
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTVDriftSegment.cc	59
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigCorrection.cc	54
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTPDeadWriter.cc	56
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0CalibrationRMS.cc	105
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0Correction.cc	41
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTNoiseComputation.cc	64
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigT0SegCorrection.cc	37
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTFakeT0ESProducer.cc	65
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0FEBPathCorrection.cc	46
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigConstantShift.cc	45
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTResidualCalibration.cc	66
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigCorrectionFirst.cc	41
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigFillWithAverage.cc	30
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0FillDefaultFromDB.cc
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/src/DTSegmentSelector.cc	71
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTVDriftWriter.cc	57
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTT0Calibration.cc	102
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigOffsetCalibration.cc	82
Deprecated API	EventSetupRecord::get function called	/CalibMuon/DTCalibration/plugins/DTTTrigResidualCorrection.cc	91
```
and
```
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTTTrigCorrection.h	DTTTrigCorrection	23	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTVDriftSegmentCalibration.h	DTVDriftSegmentCalibration	22	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTTTrigWriter.h	DTTTrigWriter	26	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTMapGenerator.h	DTMapGenerator	17	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTVDriftWriter.h	DTVDriftWriter	25	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTResidualCalibration.h	DTResidualCalibration	28	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTTPDeadWriter.h	DTTPDeadWriter	25	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTNoiseCalibration.h	DTNoiseCalibration	31	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/interface/DTCalibMuonSelection.h	DTCalibMuonSelection	15	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTT0Correction.h	DTT0Correction	20	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTT0CalibrationRMS.h	DTT0CalibrationRMS	26	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTTTrigCorrectionFirst.h	DTTTrigCorrectionFirst	20	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTTTrigOffsetCalibration.h	DTTTrigOffsetCalibration	27	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	CalibMuon/DTCalibration/plugins/DTNoiseComputation.h	DTNoiseComputation	33	1	View Report
```

**Comment by tvami** [comment]
@namapane @swagata87 FYI I created this issue just for the bookkeeping part of it

**Comment by namapane** [comment]
looks like a bit overwhelming. :-)

**Comment by tvami** [comment]
> looks like a bit overwhelming. :-)

I agree, this whole migration is a lot of manpower from all the subsystems. The positive side of it is that the software will be much faster. Btw IIUC only the first part of the list (the es get part) is what really supposed to be finished by 12_1_X, the rest (EDAnalyzers) might be fine a bit later on as well. Let me ask the release managers at the next ORP meeting.

**Comment by swagata87** [comment]
yes I have plans to work on EventSetupRecord::get issue in DT calibration code before 12_1 deadline

**Comment by swagata87** [comment]
so I was looking at EventSetupRecord::get, but only DTFakeT0ESProducer.cc is a producer code where EventSetupRecord::get is used in your list, rest are not producer code. Is it necessary to migrate in other codes? If yes, then is there any instruction how to do that? Only instruction I see explains how to migrate producer:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES

For non-producers, like most of what you listed, I don't know how to do the migration. If I try to do it same way as done for producers, it does not work. This is the error I get -> 'esConsumes' was not declared in this scope.

**Comment by tvami** [comment]
@swagata87 I clicked to the link in the issue description, then clicked to a file 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0c9c1/18662/llvm-analysis/report-14d4cb.html#EndPath

it explained there that "function 'dtCalibration::DTVDriftSegment::setES' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<DTRecoConditions> >' with argument of type 'ESHandle<class DTRecoConditions>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit"

**Comment by namapane** [comment]
@tvami I think the promlem @Swagata87 is mentioning is that e.g. DTVDriftSegment is not a ESProucer, so esConsumes() cannot be directly called therein. 
In this case, the ConsumesCollector must be percolated, which requires some update to the interface. That was the case for example for the migration of classes in #35184 (and I think the reason why it was eventually handled by Chris himself... :-) ); 
Anyhow that PR can be used as a source of examples.

**Comment by swagata87** [comment]
Partial migration of CalibMuon/DTCalibration in this PR https://github.com/cms-sw/cmssw/pull/35336
It's only partial because for some code, which are neither ESProducer, nor EDAnalyzer, migration seems non-trivial. I tried to use ConsumesCollector, but there are other issues in that approach. I haven't found a way yet..

**Comment by tvami** [comment]
Hi @swagata87 do you maybe have an update on this? 

Is this issue with 
https://github.com/cms-sw/cmssw/blob/master//CalibMuon/DTCalibration/plugins/DTVDriftSegment.cc#L55-L71
?

Can you maybe follow the exmaple here
https://github.com/cms-sw/cmssw/blob/master//CalibMuon/DTCalibration/plugins/DTVDriftSegment.cc#L55-L71 
where the token is consumed in
https://github.com/Dr15Jones/cmssw/blob/master/CalibMuon/DTDigiSync/plugins/DTTTrigSyncFromDB.cc#L132
?

**Comment by swagata87** [comment]
No I do not know how to do this. I tried and failed.
If I use `edm::ConsumesCollector` in DTVDriftSegment code, then I have issues elsewhere and package do not compile. I tried to solve it by making changes in `CalibMuon/DTCalibration/interface/DTVDriftPluginFactory.h`, but then some other code complains and do not compile. 

If you want I can type here all the errors I got. But long story short, I do not know how to migrate this code. We might need help from experts.

**Comment by tvami** [comment]
Yes, please post your errors. Even more, you could submit a Draft PR (which does not compile) so that experts can give you suggestions in the code itself (and of course to see what you are changing) . I think that's the best way to move forward! Thanks!

**Comment by namapane** [comment]
I think that the point is that in the entire muon reco sw it was a common practice to percolate the eventSetup, and interfaces have been designed accordingly. In particular, wherever there is a PluginFactory, the interface has to be modified in base object to be produced and each its implementations, plus any code that uses any of them. It is not just a class-by-class migration but an interface refactoring, that must be done for all involved pieces of code toghether, and not limited to the scope of DTCalibration (in particular, reconstruction is involved as well).

**Comment by swagata87** [comment]
ok, so I tried to use ConsumesCollector in DTVDriftSegment code, and had this issue:
```
>> Compiling edm plugin /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/DTVDriftSegment.cc
>> Compiling edm plugin /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/SealModule.cc
In file included from /cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/memory:80,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/PluginManager/interface/PluginFactory.h:23,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/maker/MakerPluginFactory.h:4,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/MakerMacros.h:4,
                 from /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/SealModule.cc:3:
/cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = dtCalibration::DTVDriftSegment; _Args = {const edm::ParameterSet&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<dtCalibration::DTVDriftSegment, std::default_delete<dtCalibration::DTVDriftSegment> >]':
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/PluginManager/interface/PluginFactory.h:56:39:   required from 'std::unique_ptr<_Tp> edmplugin::PluginFactory<R*(Args ...)>::PMaker<TPlug>::create(Args ...) const [with TPlug = dtCalibration::DTVDriftSegment; R = dtCalibration::DTVDriftBaseAlgo; Args = {const edm::ParameterSet&}]'
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/PluginManager/interface/PluginFactory.h:55:26:   required from here
/cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h:857:30: error: no matching function for call to 'dtCalibration::DTVDriftSegment::DTVDriftSegment(const edm::ParameterSet&)'
  857 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Looking at SealModule.cc, it looked like I need to change in DTVDriftPluginFactory, so I did it, but ran into other issues, I was trying to solve them following the error messages, but at the end I have this:

```
>> Compiling edm plugin /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/DTVDriftMeanTimer.cc
>> Compiling edm plugin /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/SealModule.cc
In file included from /cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/memory:80,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/PluginManager/interface/PluginFactory.h:23,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/maker/MakerPluginFactory.h:4,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/MakerMacros.h:4,
                 from /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/SealModule.cc:3:
/cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = DTVDriftWriter; _Args = {const edm::ParameterSet&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<DTVDriftWriter, std::default_delete<DTVDriftWriter> >]':
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/maker/MakeModuleHelper.h:39:40:   required from 'static std::unique_ptr<_Tp> edm::MakeModuleHelper<Base>::makeModule(const edm::ParameterSet&) [with T = DTVDriftWriter; Base = edm::EDAnalyzer]'
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/maker/WorkerMaker.h:82:107:   required from 'std::shared_ptr<edm::maker::ModuleHolder> edm::WorkerMaker<T>::makeModule(const edm::ParameterSet&) const [with T = DTVDriftWriter]'
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-28-2300/src/FWCore/Framework/interface/maker/WorkerMaker.h:76:40:   required from here
/cvmfs/cms-ib.cern.ch/nweek-02700/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/unique_ptr.h:857:30: error: no matching function for call to 'DTVDriftWriter::DTVDriftWriter(const edm::ParameterSet&)'
  857 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/SealModule.cc:17:
/afs/cern.ch/work/s/swmukher/DT_PR/CMSSW_12_1_X_2021-09-28-2300/src/CalibMuon/DTCalibration/plugins/DTVDriftWriter.h:31:3: note: candidate: 'DTVDriftWriter::DTVDriftWriter(const edm::ParameterSet&, edm::ConsumesCollector)'
   31 |   DTVDriftWriter(const edm::ParameterSet& pset, edm::ConsumesCollector);
      |   ^~~~~~~~~~~~~~

```

Its not clear to me how to proceed

**Comment by tvami** [comment]
@swagata87 my understanding is that the latest approach is to merge the header files into the cc files, and thus one doesnt even need the SealModule

**Comment by tvami** [comment]
> I think that the point is that in the entire muon reco sw it was a common practice to percolate the eventSetup, and interfaces have been designed accordingly. In particular, wherever there is a PluginFactory, the interface has to be modified in base object to be produced and each its implementations, plus any code that uses any of them. It is not just a class-by-class migration but an interface refactoring, that must be done for all involved pieces of code toghether, and not limited to the scope of DTCalibration (in particular, reconstruction is involved as well).

Ok, let me explicitly include @Dr15Jones and @makortel to see if they had something in mind already for this, or if they have a preference on how to proceed

**Comment by Dr15Jones** [comment]
So `DTVDriftWriter` is an EDAnalyzer and therefore already has the consumes collector. So the change you need from here

https://github.com/cms-sw/cmssw/blob/1b0b930c3fcf8dfdc8334d2e54b62fdfd3e408af/CalibMuon/DTCalibration/plugins/DTVDriftWriter.cc#L42-L43

is to do
```C++
      vDriftAlgo_{DTVDriftPluginFactory::get()->create(pset.getParameter<string>("vDriftAlgo"),
                                                       pset.getParameter<ParameterSet>("vDriftAlgoConfig"), 
                                                       consumesCollector())} {
```

I.e.  get the ConsumesCollector from DTVDriftWriter and pass it into the plugin factory so the different plugins can fill in the values needed.

**Comment by tvami** [comment]
Hi @swagata87 was Chris' answer helpful? Is it clear what to do next?

**Comment by swagata87** [comment]
I just had a chat with Carlo; and together we will give it another try in next days.. 
let's see

**Comment by tvami** [comment]
Hi @swagata87 sorry for being pushy, the deadline for this is until Oct 19, do you maybe have any updates?

**Comment by swagata87** [comment]
Hi Tamas, 
No worries at all. I indeed have updates on this. The rest of the DT calibration code has been migrated to use esConsumes, its in my local branch. A few final checks is being made to ensure that my changes do not affect physics and are purely technical. A PR will be made soon; let's say in a day or two.

**Comment by tvami** [comment]
Resolved in https://github.com/cms-sw/cmssw/pull/36434
