### ISSUE TITLE
Follow-up on `GeometryDB_cff` in AlCaDB related config files

### ISSUE THREAD

**Issue by mmusich** [cms-AlCaDB/AlCaTools#31]
PR https://github.com/cms-sw/cmssw/pull/35278 offers only an approximate solution to https://github.com/cms-sw/cmssw/issues/31113. 
A `GlobalTag` (or at least an `ESSource` providing the geometry records in the ES) is needed in order for `GeometryDB_cff` to work. As far as I can see, that is not included in some files touched by PR https://github.com/cms-sw/cmssw/pull/35278. Also some these might have been explicitly designed in order to take the geometry from XML.
Subsystem experts need to be contacted to decide what to do file by file (eventually none of them might really be needed).

**Comment by tvami** [comment]
@yuanchao what's the status of the issue?

**Comment by yuanchao** [comment]
The check for AlCaDB related codes are summarized in this gDoc:
https://docs.google.com/spreadsheets/d/1ZppPycBlAERR6JovCqfroH-KJtnHIbO9ozr77U2G_fY/edit?usp=sharing

**Comment by mmusich** [comment]
> Ok, I found no AlCaDB related configuration files that using Geometry_cff, so I'd like to close the issue.

That's not what this issue is about, please read carefully the description.

**Comment by mmusich** [comment]
> The check on the files touched by #35278 is included in the gDoc mentioned above.

right, so what's the plan to fix them?

**Comment by tvami** [comment]
The plan should be to move those configs to use the GT, @yuanchao can you make the PR?

**Comment by yuanchao** [comment]
Scripts out-of-dated are deleted after contacting with the sub-system experts. Those without GT are set to use auto-condition with either phase1 realistic/design or run3 data. The related PRs are listed below:

https://github.com/cms-sw/cmssw/pull/38782
https://github.com/cms-sw/cmssw/pull/38783
https://github.com/cms-sw/cmssw/pull/38796
https://github.com/cms-sw/cmssw/pull/38798

(Others with local sqlite or direct DB access are skipped as not able to test.)

**Comment by tvami** [comment]
> (Others with local sqlite or direct DB access are skipped as not able to test.)

Should those be deleted?

**Comment by yuanchao** [comment]
Deleting prior-run2 ones.

**Comment by yuanchao** [comment]
For the PRs on deleting orphan scripts, they are listed below:
cms-sw/cmssw#39011  CalibMuon/CSCCalibration (waiting for confirm from sub-det)
cms-sw/cmssw#39012 CondTools/SiPixel (suppressed by #39192)
cms-sw/cmssw#39014 Calibration/HcalAlCaRecoProducer (merged) 
cms-sw/cmssw#39150 Calibration/TkAlCaRecoProducer (suppressed by #39170)
