### ISSUE TITLE
Include BeamSpot mc tag in DD4HEP GT for RelVals

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#38]
See comment https://github.com/cms-sw/cmssw/pull/35373#issuecomment-928051202

https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1107

**Comment by tvami** [comment]
Final 12_1_X GT: 121X_mcRun3_2021_realistic_dd4hep_v3
Resolved in https://github.com/cms-sw/cmssw/pull/35373

and 12_0_X 120X_mcRun3_2021_realistic_dd4hep_v4
Resolved in https://github.com/cms-sw/cmssw/pull/35397

**Comment by mmusich** [comment]
This can be closed.
