### ISSUE TITLE
More TrackerAlignment ES get() calls

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#48]
* `Alignment/TrackerAlignment`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/TrackerAlignment
crtl-f for `.get(` finds 12 more occurrences of deprecated ES get calls  

then going to
 * `Alignment/CommonAlignmentProducer`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/CommonAlignmentProducer
I find 8 occurrences 

* `Alignment/LaserAlignmentSimulation`
src/Alignment/LaserAlignmentSimulation/test/SimAnalyzer.cc:255:67: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<TrackerGeometry>]' is deprecated [-Wdeprecated-declarations]
   255 |   theSetup.get<TrackerDigiGeometryRecord>().get(theTrackerGeometry);

* `Alignment/SurveyAnalysis`
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/SurveyAnalysis
has 16 occurrences

**Comment by tvami** [comment]
Hi @bbilin I found some more ES get()-s for your enjoyment :)

**Comment by tvami** [comment]
Hi @bbilin did you see this?

**Comment by bbilin** [comment]
Hi @tvami yes, I saw it :) I was just too busy to come to this yet, but will do so later this week. Thanks for repinging.

**Comment by tvami** [comment]
Hi @bbilin , this is my weekly kind ping :) 
As of now you'll need to change the links to a newer release for example CMSSW_12_2_CMSDEPRECATED_X_2021-11-10-2300 worked for me

**Comment by bbilin** [comment]
will ping you back as soon as I have some implementations- currently I had no time to look at it yet. Will let you know asap.

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/36193

**Comment by tvami** [comment]
Resolved in https://github.com/cms-sw/cmssw/pull/36193
