### ISSUE TITLE
More SiPixel ES get() calls

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#50]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/CondFormats/SiPixelObjects

crtl-f for `.get(` has 8 occurrences

**Comment by tvami** [comment]
I also think this should be under \plugins
Well going even further they should be under `CondTools/SiPixel`
@mmusich what was the incentive to put these readers under CondFormats?

**Comment by mmusich** [comment]
@tvami speaking only for the `SiPixelBadFEDChannel*` classes, these are mostly sanity check code and should be maintained in the test directory of `CondFormats/SiPixelObjects`. 
Eventually `SiPixelFEDChannelContainerFromQualityConverter` could be moved.

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/36016

**Comment by tvami** [comment]
resolved in https://github.com/cms-sw/cmssw/pull/36016
