### ISSUE TITLE
Rename PPS ALCARECOs

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#53]
PPS ALCARECOs have to be renamed because for the AlCaPrompt step, the AlCaPrompt producers need to have the following string in the name: "PromptCalibProd" as it is required here: https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/python/Impl/AlCa.py#L63

**Comment by grzanka** [comment]
Here is the list of PRs related to PPS ALCARECO renaming:

- https://github.com/cms-sw/cmssw/pull/36698
- https://github.com/cms-sw/cmssw/pull/36702
-  https://github.com/cms-sw/cmssw/pull/36707

**Comment by tvami** [comment]
Plus the addition to the autoAlca in 
https://github.com/cms-sw/cmssw/pull/36730

**Comment by tvami** [comment]
Resolved in https://github.com/cms-sw/cmssw/pull/36702
