### ISSUE TITLE
Create new relval workflows for @allForExpress and @allForPrompt (from autoAlCa.py) with 2022 collision data.

### ISSUE THREAD

**Issue by malbouis** [cms-AlCaDB/AlCaTools#65]
Currently the workflows to test all AlCaRecos (@allForPrompt and @allForExpress) use either Run-1 (relval workflow [1000](https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_production.py#L12)) or Run-2 data (relval workflow [1001.2](https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_production.py#L14)).

They should be updated to use Run-3 data.

**Comment by malbouis** [comment]
@tocheng

**Comment by tvami** [comment]
@tocheng this is the also connected to what I asked in the other github issue

**Comment by tvami** [comment]
Being resolved in https://github.com/cms-sw/cmssw/pull/38681/

**Comment by tvami** [comment]
Resolved in https://github.com/cms-sw/cmssw/pull/38681
