### ISSUE TITLE
Remove hardcoded trigger bits from AlCaRecos and include it as a key in the alcareco trigger bits tag.

### ISSUE THREAD

**Issue by malbouis** [cms-AlCaDB/AlCaTools#70]
The following AlCaRecos were found to have hardcoded trigger bits:

   * https://github.com/cms-sw/cmssw/blob/master/Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_cff.py#L10
      * update the key to `SiPixelCalSingleMuon` as per [this comment](https://github.com/cms-AlCaDB/AlCaTools/issues/70#issuecomment-1197779253).
   * https://github.com/cms-sw/cmssw/blob/master/Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCRandom_cff.py#L5
   * https://github.com/cms-sw/cmssw/blob/master/Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCZeroBias_cff.py#L5

This issue is for:
   1. Verify if there are corresponding keys in the current alcarecotriggerbits tag.
      * if not, add the corresponding keys to the alcarecotriggerbits tag and create a new tag.
   2. Once the new tag is created and added to the GTs, make a PR to CMSSW to replace the hardcoded trigger bits by their corresponding keys.

**Comment by malbouis** [comment]
assign @cms-AlCaDB/alca-tsg

**Comment by malbouis** [comment]
type tsg

**Comment by mmusich** [comment]
Hi,
to clarify

> The following AlCaRecos were found to have hardcoded trigger bits:

> https://github.com/cms-sw/cmssw/blob/master/Alignment/CommonAlignmentProducer/python/ALCARECOTkAlDiMuonAndVertex_cff.py#L7


This is not hardcoded, it clones the one for `TkAlZMuMu` which is coming from GlobalTag.
The current logic ensures the two are always synched. Please don't change the behavior.
Thx

**Comment by malbouis** [comment]
Hi! My bad, I included the wrong link!
I meant this: https://github.com/cms-sw/cmssw/blob/master/Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonTight_cff.py#L10
If you agree, we would like to set it as `SiPixelCalSingleMuonTight` as indicated in the comments.
Please ket us know.

**Comment by mmusich** [comment]
> Please ket us know.

There's already a key 'SiPixelCalSingleMuon' used in the loose version.

https://github.com/cms-sw/cmssw/blob/717889207b43821a481d4491298f48363a8c9e5e/Calibration/TkAlCaRecoProducers/python/ALCARECOSiPixelCalSingleMuonLoose_cff.py#L10

I think the two could share the same key.

**Comment by mmusich** [comment]
> I think the two could share the same key.

I address this here: https://github.com/cms-sw/cmssw/pull/39025

**Comment by malbouis** [comment]
solved by https://github.com/cms-sw/cmssw/pull/39025 and https://github.com/cms-sw/cmssw/pull/39752
