### ISSUE TITLE
Move `PCLMetadataWriter` to `CommonTools`

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#72]
Move `Calibration/TkAlCaRecoProducers/plugins/PCLMetadataWriter.cc` to `CommonTools`

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/39002 for a possible solution.

**Comment by tvami** [comment]
Resolved in https://github.com/cms-sw/cmssw/pull/39002
