### ISSUE TITLE
conddb dump behaviour changes if ` --destfile` is specified

### ISSUE THREAD

**Issue by tvami** [cms-AlCaDB/AlCaTools#89]
conddb dump behaviour changes if ` --destfile` is specified on multi-IOV tags.

```
conddb dump HcalRecoParams_v11.1_offline
```
shows all the IOVs
while
```
conddb dump HcalRecoParams_v11.1_offline --destfile HcalRecoParams_v11.1_offline.xml
```
outputs only one payload.

**Comment by francescobrivio** [comment]
Originally the `dump` functionality was only implemented for the payload, while for tag and GT it was throwing an error.
This was fixed already in https://github.com/cms-sw/cmssw/pull/38757, but I guess we didn't take into account the multi-IOV tags (which I'm not sure how they should be treated...).
We (me and Ilya) will take a look at it.

**Comment by tvami** [comment]
one thing that I've not tried is to see if the functionality changes back in case the `type` is specified
```
conddb dump --type tag HcalRecoParams_v11.1_offline --destfile HcalRecoParams_v11.1_offline.xml
```
vs
```
conddb dump HcalRecoParams_v11.1_offline
```

**Comment by francescobrivio** [comment]
> one thing that I've not tried is to see if the functionality changes back in case the `type` is specified
> 
> ```
> conddb dump --type tag HcalRecoParams_v11.1_offline --destfile HcalRecoParams_v11.1_offline.xml
> ```
> 
> vs
> 
> ```
> conddb dump HcalRecoParams_v11.1_offline
> ```

I have tried it, and specifying  `--type tag` doesn't change the wrong behavior.

**Comment by tvami** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/42604
